coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "**/ui/app.py"
  - "**/ui/viewer.py"
  - "**/ui/remeshing.py"
  - "**/ui/__init__.py"
  - "**/ui/__main__.py"
  - "**/interactive/**"
