name: Build and Test

on:
  push:
    branches: [main]
  pull_request: # Any pull request
  workflow_dispatch: # Allow manual triggering of the workflow
  schedule:
    - cron: "0 0 * * *" # Run at midnight UTC every day

env:
  VTK_VERSION_MAJOR: 9
  VTK_VERSION_MINOR: 3
  VTK_VERSION_PATCH: 1

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - "3.9"
          - "3.13"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # Install VTK 9.3 using apt for Ubuntu
      - name: Install VTK (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libvtk9-dev

      # Install VTK 9.3 using homebrew for macOS
      - name: Install VTK (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install vtk

      # Download and extract pre-built VTK 9.3.1 for Windows
      - name: Download pre-built VTK (Windows)
        if: runner.os == 'Windows'
        uses: suisei-cn/actions-download-file@v1.0.1
        with:
          url: https://github.com/sanguinariojoe/vtk-builds/releases/download/VTK-${{env.VTK_VERSION_MAJOR}}.${{env.VTK_VERSION_MINOR}}.${{env.VTK_VERSION_PATCH}}-static/vtk-${{runner.os}}-x86_64.tar.gz
          target: ${{github.workspace}}/

      - name: Extract VTK (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir -p "${{github.workspace}}/vtk"
          tar -xvzf "${{github.workspace}}/vtk-Windows-x86_64.tar.gz" -C "${{github.workspace}}/vtk"
          echo "VTK_DIR=${{github.workspace}}/vtk/lib/cmake/vtk-${{env.VTK_VERSION_MAJOR}}.${{env.VTK_VERSION_MINOR}}" >> $GITHUB_ENV
        shell: bash

      - uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: uv sync -v
      - run: uv run pytest
