# .github/workflows/build.yml
name: Build Wheels

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-wheels:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - macos-13

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - uses: pypa/cibuildwheel@v3.0
      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
          retention-days: 30 # Keep artifacts for 30 days

  build-sdist:
    needs: build-wheels
    runs-on: ubuntu-latest
    name: Build source distribution

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6

      - name: Build source distribution
        run: uv build --sdist

      - name: Upload sdist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          retention-days: 30
