name: Build Wheels

on:
  workflow_dispatch:
    inputs:
      publish_to_testpypi:
        description: "Publish to TestPyPI"
        required: false
        default: false
        type: boolean
      publish_to_pypi:
        description: "Publish to PyPI"
        required: false
        default: false
        type: boolean
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-wheels:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - macos-13

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - uses: pypa/cibuildwheel@v3.0
      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  build-sdist:
    needs: build-wheels
    runs-on: ubuntu-latest
    name: Build source distribution

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6

      - name: Build source distribution
        run: uv build --sdist

      - name: Upload sdist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  publish-to-testpypi:
    needs: [build-wheels, build-sdist]
    runs-on: ubuntu-latest
    name: Publish to TestPyPI
    if: >
      (github.event_name == 'workflow_dispatch' && inputs.publish_to_testpypi) ||
      (github.event_name == 'push' && github.ref == 'refs/heads/master')
    environment:
      name: testpypi
      url: https://test.pypi.org/p/${{ github.event.repository.name }}

    permissions:
      id-token: write # For trusted publishing

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    needs: [build-wheels, build-sdist]
    runs-on: ubuntu-latest
    name: Publish to PyPI
    # Only publish to PyPI on manual trigger with pypi option
    if: github.event_name == 'workflow_dispatch' && inputs.publish_to_pypi

    environment:
      name: pypi
      url: https://pypi.org/p/${{ github.event.repository.name }}

    permissions:
      id-token: write # For trusted publishing

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
