name: Build and Test

on:
  push:
    branches: [main]
  pull_request: # Any pull request
  workflow_dispatch: # Allow manual triggering of the workflow
  schedule:
    - cron: "0 0 * * *" # Run at midnight UTC every day

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - "3.9"
          - "3.13"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install VTK using system package manager
      - name: Install VTK (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libvtk9-dev

      - name: Install VTK (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install vtk

      - name: Install VTK (Windows)
        if: runner.os == 'Windows'
        run: |
          vcpkg install vtk:x64-windows

      - run: uv sync -v
      - run: uv run pytest
