name: Build and Test

on:
  push:
    branches: [main]
  pull_request: # Any pull request
  workflow_dispatch: # Allow manual triggering of the workflow
  schedule:
    - cron: "0 0 * * *" # Run at midnight UTC every day

jobs:
  install-vtk:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    uses: ./.github/workflows/install-vtk.yml
    with:
      os: ${{ matrix.os }}
      vtk_major: "9"
      vtk_minor: "3"
      vtk_patch: "1"

  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - "3.9"
          - "3.13"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set CMake path
        run: echo "CMAKE_PREFIX_PATH=${{ needs.install-vtk.outputs.cmake_prefix_path }}" >> $GITHUB_ENV

      - run: echo ${{ needs.install-vtk.outputs.cmake_prefix_path }}

      - run: uv sync -v
      - run: uv run python -c "import mmgpy"
      - run: uv run pytest -s
