name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Build Wheels"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      run_id:
        description: "Build Wheels workflow run ID to download artifacts from"
        required: true
        type: string

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    name: Publish to PyPI
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'release') || github.event_name == 'workflow_dispatch' }}

    environment:
      name: pypi
      url: https://pypi.org/p/${{ github.event.repository.name }}

    permissions:
      id-token: write # For trusted publishing
      actions: read # To download artifacts from other workflows

    steps:
      - name: Download artifacts from build workflow
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id || inputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-multiple: true
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
