name: Publish to PyPI
on:
  push:
    tags:
      - "v*"
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, macos-13] #, ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build package
        run: uv build --no-sources
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/*

  upload:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.12"
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true
      - name: List distributions
        run: ls -R dist/
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish dist/* --verbose
      - name: Rename wheels for TestPyPI
        if: github.event_name == 'pull_request'
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          for wheel in dist/*.whl; do
              # Extract version from wheel filename
              CURRENT_VERSION=$(echo "$wheel" | sed -E 's/.*-([0-9]+\.[0-9]+\.[0-9]+.*)-.*\.whl/\1/')
              NEW_VERSION="${CURRENT_VERSION}.dev+git.${COMMIT_HASH}"
              # Replace version in filename
              NEW_NAME=$(echo "$wheel" | sed "s/$CURRENT_VERSION/$NEW_VERSION/")
              mv "$wheel" "$NEW_NAME"
          done
          for sdist in dist/*.tar.gz; do
              if [ -f "$sdist" ]; then
                  CURRENT_VERSION=$(echo "$sdist" | sed -E 's/.*-([0-9]+\.[0-9]+\.[0-9]+.*).tar.gz/\1/')
                  # Create new name in desired format: mmgpy.dev+git.hash-version.tar.gz
                  NEW_NAME="dist/mmgpy.dev+git.${COMMIT_HASH}-${CURRENT_VERSION}.tar.gz"
                  mv "$sdist" "$NEW_NAME"
              fi
          done
      - name: Publish to TestPyPI
        if: github.event_name == 'pull_request'
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
        run: uv publish dist/* --publish-url https://test.pypi.org/legacy/ --verbose
