name: Publish to PyPI
on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, macos-13] #, ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}

      # VTK Installation steps
      - name: Set VTK filename
        id: vtk-file
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "filename=vtk-Windows-x86_64.tar.gz" >> $GITHUB_OUTPUT
          elif [ "$RUNNER_OS" == "Linux" ]; then
            echo "filename=vtk-manylinux2014_x86_64.tar.gz" >> $GITHUB_OUTPUT
          elif [ "$RUNNER_OS" == "macOS" ]; then
            if [ "$(uname -m)" == "arm64" ]; then
              echo "filename=vtk-macOS-arm64.tar.gz" >> $GITHUB_OUTPUT
            else
              echo "filename=vtk-macOS-x86_64.tar.gz" >> $GITHUB_OUTPUT
            fi
          fi
        shell: bash

      - name: Download pre-built VTK
        uses: suisei-cn/actions-download-file@v1.6.0
        with:
          url: https://github.com/sanguinariojoe/vtk-builds/releases/download/VTK-${{env.VTK_VERSION_MAJOR}}.${{env.VTK_VERSION_MINOR}}.${{env.VTK_VERSION_PATCH}}-static/${{ steps.vtk-file.outputs.filename }}
          target: ${{github.workspace}}

      - name: Extract VTK
        run: |
          mkdir -p vtk
          tar -xzf ${{ steps.vtk-file.outputs.filename }} -C vtk
        shell: bash
        working-directory: ${{github.workspace}}

      - name: Set CMake path
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            VTK_PATH=$(cygpath -w "${PWD}/vtk/lib/cmake/vtk-${VTK_VERSION_MAJOR}.${VTK_VERSION_MINOR}" | sed 's/\\/\\\\/g')
          elif [ "$RUNNER_OS" == "Linux" ]; then
            VTK_PATH="${PWD}/vtk/lib64/cmake/vtk-${VTK_VERSION_MAJOR}.${VTK_VERSION_MINOR}"
            echo "LD_LIBRARY_PATH=${PWD}/vtk/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          else
            VTK_PATH="${PWD}/vtk/lib/cmake/vtk-${VTK_VERSION_MAJOR}.${VTK_VERSION_MINOR}"
          fi
          echo "CMAKE_PREFIX_PATH=${VTK_PATH}" >> $GITHUB_ENV
        shell: bash
        working-directory: ${{github.workspace}}

      - name: Build package
        run: uv build --no-sources
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/*

  upload:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.12"
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true
      - name: List distributions
        run: ls -R dist/
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish dist/* --verbose
      - name: Rename wheels for TestPyPI
        if: github.event_name == 'pull_request'
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          for wheel in dist/*.whl; do
              # Extract version from wheel filename
              CURRENT_VERSION=$(echo "$wheel" | sed -E 's/.*-([0-9]+\.[0-9]+\.[0-9]+.*)-.*\.whl/\1/')
              NEW_VERSION="${CURRENT_VERSION}.dev+git.${COMMIT_HASH}"
              # Replace version in filename
              NEW_NAME=$(echo "$wheel" | sed "s/$CURRENT_VERSION/$NEW_VERSION/")
              mv "$wheel" "$NEW_NAME"
          done
          for sdist in dist/*.tar.gz; do
              if [ -f "$sdist" ]; then
                  CURRENT_VERSION=$(echo "$sdist" | sed -E 's/.*-([0-9]+\.[0-9]+\.[0-9]+.*).tar.gz/\1/')
                  # Create new name in desired format: mmgpy.dev+git.hash-version.tar.gz
                  NEW_NAME="dist/mmgpy.dev+git.${COMMIT_HASH}-${CURRENT_VERSION}.tar.gz"
                  mv "$sdist" "$NEW_NAME"
              fi
          done
      - name: Publish to TestPyPI
        if: github.event_name == 'pull_request'
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
        run: uv publish dist/* --publish-url https://test.pypi.org/legacy/ --verbose
